[ECO-1177] Show total refunded in seller view.
mobbexco/magento-2-marketplace pull request #38
Opened 2024-12-16 15:15 UTC by EMunozMobbex

2024-12-16 19:32 UTC, mobbexLuis approved these changes

2024-12-17 15:07 UTC, jlmobbex requested changes

2024-12-17 15:07 UTC, jlmobbex commented on Observer/Hooks.php
> +
Esto se puede resolver en menos líneas usando la función `array_sum()` (ver como se realiza esta misma suma en el archivo Info.php del plugin principal).

2025-02-14 14:08 UTC, jlmobbex approved these changes

2025-02-14 14:08 UTC, merged